# Load NumPY

In [1]:
import numpy as np  

# The Basics

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
#two dimensional array(should have equal elements in all role)
b = np.array([[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 9.0, 10.0, 11.0]])
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  9. 10. 11.]]


In [4]:
#Three Dimensional arrays(equal number of elements)
c = np.array([[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 9.0, 10.0, 11.0], [1.0, 2.0, 3.0, 4.0, 5.0]])
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  9. 10. 11.]
 [ 1.  2.  3.  4.  5.]]


## get Dimensions

In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
c.ndim

2

## get shape

In [8]:
a.shape

(5,)

In [9]:
b.shape

(2, 5)

In [10]:
c.shape

(3, 5)

## get Type

In [11]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [13]:
c.dtype

dtype('float64')

## get size (bytes)
we can also resize the array (dtype = 'int16') and a=2.

In [14]:
a.itemsize

4

In [15]:
b.itemsize

8

In [16]:
c.itemsize

8

## get total size

In [17]:
a.nbytes

20

In [18]:
b.nbytes

80

In [19]:
c.nbytes

120

# Accessing/changing specific elements, rows, columns, etc.

## 2-Dimensional array

In [20]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
#get a specific element [row,colume] i.e [r,c]

a[1,5]  # or a[1, -2]

13

In [42]:
#get a specific row

a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
#get  a specific column

a[:,2]

array([ 3, 10])

In [53]:
#[startindex:endindex:stepsize]

a[0, 1:6:2]  # or a[0, 1:-1:2]

array([2, 4, 6])

In [56]:
#Replacement

#13 in a to 20

a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [57]:
#Replacing  colum 2

a[:,2] = 5 #replace all to 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [60]:
#Replacing  colum 2 with diferent values

a[:,2] = [11,12]
print(a)

[[ 1  2 11  4  5  6  7]
 [ 8  9 12 11 12 20 14]]


## 3-Dimensioal array example

In [23]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
#Get a specific element
b[0,1,1] #b[0,1,o] = 3

4

In [31]:
#display second rows in each array
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [32]:
#Replace second rows in each array
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays 

In [38]:
#All 0s Matrix

#np.zeros(5)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
#All 1s Matrix

np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
#Any other number
#takes in two figure, the shape and the value
np.full((2,2), 99) 

array([[99, 99],
       [99, 99]])

In [55]:
# Another number full_like
#the array(a) values can be replace

#np.full_like(a.shape, 2) or
np.full_like(a,2)


array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [60]:
#Random Decimal numbes

np.random.rand(4,2) # random (4,2) matrix
np.random.random_sample(a.shape) # generate random flaot of the array(a)

array([[0.03479388, 0.8044858 , 0.14841253, 0.30990127, 0.94693436,
        0.85122397, 0.02430835],
       [0.93225651, 0.83590416, 0.98099982, 0.70980232, 0.4231677 ,
        0.59738097, 0.47891437]])

In [74]:
#Random intege values.
#Generate int btw -4 and 7 with a size of (3,3) matrix

#np.random.randint(5, size=(a.shape))
np.random.randint(-4,7,size=(3,3)) 

array([[ 1,  5,  2],
       [ 6, -4,  1],
       [ 1,  3,  2]])

In [75]:
#the identity martrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])