# Load NumPY

In [1]:
import numpy as np  

# The Basics

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
#two dimensional array(should have equal elements in all role)
b = np.array([[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 9.0, 10.0, 11.0]])
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  9. 10. 11.]]


In [8]:
#Three Dimensional arrays(equal number of elements)
c = np.array([[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 9.0, 10.0, 11.0], [1.0, 2.0, 3.0, 4.0, 5.0]])
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  9. 10. 11.]
 [ 1.  2.  3.  4.  5.]]


## get Dimensions

In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [11]:
c.ndim

2

## get shape

In [12]:
a.shape

(5,)

In [13]:
b.shape

(2, 5)

In [14]:
c.shape

(3, 5)

## get Type

In [15]:
a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('float64')

In [17]:
c.dtype

dtype('float64')

## get size (bytes)
we can also resize the array (dtype = 'int16') and a=2.

In [18]:
a.itemsize

4

In [19]:
b.itemsize

8

In [20]:
c.itemsize

8

## get total size

In [21]:
a.nbytes

20

In [22]:
b.nbytes

80

In [23]:
c.nbytes

120

# Accessing/changing specific elements, rows, columns, etc.

## 2-Dimensional array

In [29]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
#get a specific element [row,colume] i.e [r,c]

a[1,5]  # or a[1, -2]

13

In [31]:
#get a specific row

a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
#get  a specific column

a[:,2]

array([ 3, 10])

In [33]:
#[startindex:endindex:stepsize]

a[0, 1:6:2]  # or a[0, 1:-1:2]

array([2, 4, 6])

In [34]:
#Replacement

#13 in a to 20

a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [35]:
#Replacing  colum 2

a[:,2] = 5 #replace all to 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [36]:
#Replacing  colum 2 with diferent values

a[:,2] = [11,12]
print(a)

[[ 1  2 11  4  5  6  7]
 [ 8  9 12 11 12 20 14]]


## 3-Dimensioal array example

In [38]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
#Get a specific element
b[0,1,1] #b[0,1,o] = 3

4

In [40]:
#display second rows in each array
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [41]:
#Replace second rows in each array
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays 

In [42]:
#All 0s Matrix

#np.zeros(5)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
#All 1s Matrix

np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
#Any other number
#takes in two figure, the shape and the value
np.full((2,2), 99) 

array([[99, 99],
       [99, 99]])

In [55]:
# Another number full_like
#the array(a) values can be replace

#np.full_like(a.shape, 2) or
np.full_like(a,2)


array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [60]:
#Random Decimal numbes

np.random.rand(4,2) # random (4,2) matrix
np.random.random_sample(a.shape) # generate random flaot of the array(a)

array([[0.03479388, 0.8044858 , 0.14841253, 0.30990127, 0.94693436,
        0.85122397, 0.02430835],
       [0.93225651, 0.83590416, 0.98099982, 0.70980232, 0.4231677 ,
        0.59738097, 0.47891437]])

In [74]:
#Random intege values.
#Generate int btw -4 and 7 with a size of (3,3) matrix

#np.random.randint(5, size=(a.shape))
np.random.randint(-4,7,size=(3,3)) 

array([[ 1,  5,  2],
       [ 6, -4,  1],
       [ 1,  3,  2]])

In [75]:
#the identity martrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
#Repeat array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
#exercise

output = np.ones((5,5))
print(output)

print(' ')

z = np.zeros((3,3))
print(z)

print(' ')

z[1,1] = 9
print(z)



output[1:-1,1:-1] = z

print(' ')

print(output)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Copying an Array

In [50]:
# When copying an array remember to use the copy() method, 
#else the previous variable updates to whatever input the present variable takes

a = np.array([1,2,3])
b = a.copy()

b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics 

## Arithmetics 

In [52]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [54]:
a + 2 #or a += 2, then print(a)

array([3, 4, 5, 6])

In [55]:
a - 2

array([-1,  0,  1,  2])

In [56]:
a * 2 

array([2, 4, 6, 8])

In [57]:
a / 2 

array([0.5, 1. , 1.5, 2. ])

In [58]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [59]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

## Take the sin

In [62]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [63]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [64]:
np.sinc(a)

array([ 3.89817183e-17, -3.89817183e-17,  3.89817183e-17, -3.89817183e-17])

In [65]:
np.cosh(a)

array([ 1.54308063,  3.76219569, 10.067662  , 27.30823284])

## Linear Algebra

In [70]:
## In Linear Algebra the rows of the first Matrix. must be equal to the columns of second Matrix.

a = np.ones([2,3])
print(a)

b = np.full([3,2], 2)
print(b)

print('')

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]



array([[6., 6.],
       [6., 6.]])