# Load NumPY

In [ ]:
import numpy as np  

# The Basics

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [14]:
#two dimensional array(should have equal elements in all role)
b = np.array([[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 9.0, 10.0, 11.0]])
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  9. 10. 11.]]


In [15]:
#Three Dimensional arrays(equal number of elements)
c = np.array([[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 9.0, 10.0, 11.0], [1.0, 2.0, 3.0, 4.0, 5.0]])
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  9. 10. 11.]
 [ 1.  2.  3.  4.  5.]]


## get Dimensions

In [17]:
a.ndim

1

In [18]:
b.ndim

2

In [19]:
c.ndim

2

## get shape

In [20]:
a.shape

(5,)

In [21]:
b.shape

(2, 5)

In [22]:
c.shape

(3, 5)

## get Type

In [23]:
a.dtype

dtype('int32')

In [24]:
b.dtype

dtype('float64')

In [25]:
c.dtype

dtype('float64')

## get size (bytes)
we can also resize the array (dtype = 'int16') and a=2.

In [26]:
a.itemsize

4

In [27]:
b.itemsize

8

In [28]:
c.itemsize

8

## get total size

In [29]:
a.nbytes

20

In [30]:
b.nbytes

80

In [31]:
c.nbytes

120

# Accessing/changing specific elements, rows, columns, etc.

In [33]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
#get a specific element [row,colume] i.e [r,c]

a[1,5]  # or a[1, -2]

13

In [42]:
#get a specific row

a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
#get  a specific column

a[:,2]

array([ 3, 10])

In [53]:
#[startindex:endindex:stepsize]

a[0, 1:6:2]  # or a[0, 1:-1:2]

array([2, 4, 6])