# Load NumPY

In [ ]:
import numpy as np  

# The Basics

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [14]:
#two dimensional array(should have equal elements in all role)
b = np.array([[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 9.0, 10.0, 11.0]])
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  9. 10. 11.]]


In [15]:
#Three Dimensional arrays(equal number of elements)
c = np.array([[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 9.0, 10.0, 11.0], [1.0, 2.0, 3.0, 4.0, 5.0]])
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  9. 10. 11.]
 [ 1.  2.  3.  4.  5.]]
